server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/account
    username: khoapd
    password: khoapd
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


springdoc:
  api-docs:
    enabled: true
    path: /account/v3/api-docs
  swagger-ui:
    enabled: true
